name: amun
evaluate_each_epoch: true
trainer:
  max_epochs: 10
optim:
  name: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0
  nesterov: false
  betas: [0.9, 0.999]
  exclude_wd_norm_bias: true
scheduler:
  name: none
attack:
  epsilon_init: 0.1
  steps: 50
  step_factor: 0.1
  max_rounds: 6
use_weighted_loss: false
retain_weight: 0.5
forget_weight: ${eval:1 - ${.retain_weight}}
use_retain: true                 # config D_A ∪ D_f ∪ D_r (cân bằng nhất)
use_forget: true
