name: l1sparse
evaluate_each_epoch: true
trainer:
  max_epochs: 10
optim:
  name: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0
  nesterov: false
  betas: [0.9, 0.999]
  exclude_wd_norm_bias: true
scheduler:
  name: none
l1:
  gamma: 0.0005                  # giữa range [5e-6, 5e-3]
  schedule: linear_decay
