name: scrub
evaluate_each_epoch: true
alpha: 0.5
gamma: 1.0
temperature: 4.0
trainer:
  max_epochs: 5
optim:
  name: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 0
  nesterov: false
  betas: [0.9, 0.999]
  exclude_wd_norm_bias: true
scheduler:
  name: multistep
  milestones: [3]                # 🔥 bỏ 5,9 (max_epochs=5 không chạm tới)
  gamma: 0.1
